zeta-chain/localnet

- packages/localnet/src/index.ts
covering flow:
- GatewayEVM.execute called with address of Hello contract from example-contracts
- worker picks up Called event and forwards call to Hello contract's onCrossChainCall
- onCrossChainCall reverts
- worker calls GatewayEVM.executeRevert using RevertOptions from Called event
is this useful? also it seems localnet in general needs some modifications, for example currently it was broken because zrc20 contract was missing - in this case, onCrossChainCall expects zrc20 to be passed as arg, which zrc20 we would send if localnet doesn't deploy some?
> add revert handling

- packages/localnet/src/index.ts
The only change aside from formatting is using `protocolContracts.zrc20Eth.target` inside `protocolContracts.gatewayEVM.on("Deposited"...`
> fix: calling a universal contract using depositAndCall

- package.json
- packages/localnet/src/index.ts
- packages/tasks/src/localnet.ts
- yarn.lock
Nicer output to make it easier for developer to distinguish actions happening on EVM vs ZetaChain.
* Protocol contracts addresses output during initialization
* onCrossChainCall with params
* Printing events. Events are not decoded for now (we need ABI for this), but it's better than nothing. We can also modify the interact task to watch for events after broadcasting a tx and decoding them.
* set ZRC-20 withdraw fee using the system contract
Using Ansis not Chalk for colors, because Chalk doesn't support TS.
> feat: improve logging

- packages/localnet/src/createToken.ts
- packages/localnet/src/deployOpts.ts
- packages/localnet/src/handleOnEVMCalled.ts
- packages/localnet/src/handleOnEVMDeposited.ts
- packages/localnet/src/handleOnRevertEVM.ts
- packages/localnet/src/handleOnRevertZEVM.ts
- packages/localnet/src/handleOnZEVMCalled.ts
- packages/localnet/src/handleOnZEVMWithdrawn.ts
- packages/localnet/src/index.ts
- packages/localnet/src/log.ts
- packages/tasks/src/localnet.ts
* Correct decimals when adding ZRC-20 liquidity
* Logging
* Handle ZRC-20 correctly when depositing ERC-20
* added `foreignCoins` array to match [`/foreignCoins`](https://zetachain-athens.blockpi.network/lcd/v1/public/zeta-chain/fungible/foreign_coins) endpoint
> Added handling of ERC-20 deposits

- packages/localnet/src/createToken.ts
Set the correct coin type based on whether a token is gas or ERC-20.
> fix: set correct ZRC-20 coin type

- .github/workflows/run.yml
- hardhat.config.ts
- package.json
- packages/localnet/src/createToken.ts
- packages/tasks/src/index.ts
- packages/tasks/src/localnet.ts
- packages/tasks/src/stop.ts
- yarn.lock
A bunch of quality of life improvements.
- added a task to stop localnet. This could be used for integration testing: start localnet, run some command, if they succeed kill localnet.
- prompt user to kill a process running on the same port as anvil
- clean up if localnet init fails
- format addresses into tables
```
EVM Contract Addresses
=======================
┌─────────────────┬──────────────────────────────────────────────┐
│ (index)         │ Values                                       │
├─────────────────┼──────────────────────────────────────────────┤
│ Gateway EVM     │ '0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0' │
│ ERC-20 Custody  │ '0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9' │
│ TSS             │ '0x70997970C51812dc3A010C7d01b50e0d17dc79C8' │
│ ZETA            │ …
```
> feat: task to stop localnet

- README.md
Updating the readme with the tables shown in the command 
```
EVM Contract Addresses
=======================
┌─────────────────┬──────────────────────────────────────────────┐
│     (index)     │                    Values                    │
├─────────────────┼──────────────────────────────────────────────┤
│   Gateway EVM   │ '0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0' │
│ ERC-20 Custody  │ '0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9' │
│       TSS       │ '0x70997970C51812dc3A010C7d01b50e0d17dc79C8' │
│      ZETA       │ '0x5FbDB2315678afecb367f032d93F642f64180aa3' │
│ ERC-20 USDC.ETH │ '0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82' │
└─────────────────┴──────────────────────────────────────────────┘
ZetaChain Contract Addresses
============================= …
```
> docs: update readme with start output

- .gitignore
- packages/tasks/src/localnet.ts
Apparently, multiple processes can use the same port (based on the output of `lsof -ti tcp:${port}`). This PR allows the user to kill all processes in one go.
Also, added `lolcanet.pid` to gitignore.
> feat: allow user to kill all processes on a given port

- packages/localnet/src/createToken.ts
USDC ZRC-20 was set as gas token incorrectly (should be ETH).
> fix: set ZRC-20 gas token correctly

- packages/localnet/src/handleOnEVMCalled.ts
- packages/localnet/src/handleOnEVMDeposited.ts
- packages/localnet/src/handleOnRevertEVM.ts
- packages/localnet/src/handleOnRevertZEVM.ts
- packages/localnet/src/handleOnZEVMCalled.ts
- packages/localnet/src/handleOnZEVMWithdrawn.ts
- packages/localnet/src/index.ts
- packages/tasks/src/localnet.ts
- packages/tasks/src/stop.ts
* `--exit-on-error` flag to kill localnet if revert fails or tx reverted without call on revert. This could be useful in CI, where you want localnet to fail if something goes wrong
* refactored the stop task to remove `localnet.pid` if if exists, but the localnet is not running (it cannot cleanup after itself and delete pid if it's not running)
> feat: `--exit-on-error` flag

- README.md
The address of ZRC-20 ETH.ETH had not been updated, so I've updated it now. It changed during the last few commits that were made.
> Update ETH.ETH address

- packages/localnet/src/handleOnZEVMWithdrawn.ts
* If the message is not empty (meainng it was a withdraw and call),
* if native gas, we call gatewayEVM.execute
* if ERC-20 or ZETA, we call  gatewayEVM.executeWithERC20
* If the message is empty (meaning it was a withdraw)
* if it's native gas, then we transfer from TSS to receiver
* if it's ERC-20 or ZETA, we transfer from ERC-20 custody contract to receiver
> handle withdraw

- packages/localnet/src/createToken.ts
- packages/localnet/src/handleOnRevertZEVM.ts
- packages/localnet/src/handleOnZEVMCalled.ts
- packages/localnet/src/handleOnZEVMWithdrawn.ts
- packages/localnet/src/index.ts
* Emit events when a transaction reverts
* `withdrawAndCall` ERC-20s
> Handle `withdrawAndCall` with ERC-20s and emit events on revert

- packages/localnet/src/createToken.ts
- packages/localnet/src/handleOnEVMCalled.ts
- packages/localnet/src/handleOnEVMDeposited.ts
- packages/localnet/src/handleOnRevertEVM.ts
- packages/localnet/src/handleOnRevertZEVM.ts
- packages/localnet/src/handleOnZEVMCalled.ts
- packages/localnet/src/handleOnZEVMWithdrawn.ts
- packages/localnet/src/index.ts
- packages/tasks/src/localnet.ts
```
npx hardhat localnet
```
Using [the Hello example](https://github.com/zeta-chain/example-contracts/tree/893d2bf110e33780659d2bc470868aec4017dc27/examples/hello):
```
yarn deploy
```
The Hello contract expects a string, so we're sending a uint256 to simulate a revert. Passing 1*10^18 ERC-20, and getting `999999999992957809`, which is the amount minus the withdraw gas costs
```
npx hardhat evm-deposit-and-call --amount 1 --receiver 0xE6E340D132b5f46d1e472DebcD681B2aBc16e57E --network localhost --revert-address 0xc3e53F4d16Ae77Db1c982e75a937B9f60FE63690 --erc20 0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82 --call-on-revert --types '["uint256"]' 42
```
With gas we're getting back 999999999993000000:
```
npx hardhat evm-deposit-and-call --amount 1 --receiver …
```
> Fix revert handling

- .github/workflows/release-to-discord.yml
Automatically publish release information to a Discord channel. The channel is temporarily private until this works as expected.
> ci: publish releases to Discord

- .github/workflows/release-to-discord.yml
Couldn't find the version of the action: https://github.com/zeta-chain/localnet/actions/runs/11439296753
Updated to a specific up-to-date version.
> fix: discord release

- .github/workflows/release-to-discord.yml
Added an avatar image, removed extra properties.
Also, don't publish releases with `-` in name (release candidates like `v1.0.0-rc1`).
> Release to Discord: update image URL

- hardhat.config.ts
- packages/tasks/src/check.ts
- packages/tasks/src/index.ts
A task to check if `localnet` is still running. Useful for CI for testing example contracts:
```
#!/bin/bash
set -e
npx hardhat localnet --exit-on-error &
sleep 5
yarn deploy
npx hardhat echo-call \
--contract 0xc3e53F4d16Ae77Db1c982e75a937B9f60FE63690 \
--receiver 0xE6E340D132b5f46d1e472DebcD681B2aBc16e57E \
--network localhost \
--types '["string"]' alice
npx hardhat localnet-check
npx hardhat echo-call \
--contract 0xc3e53F4d16Ae77Db1c982e75a937B9f60FE63690 \
--receiver 0xE6E340D132b5f46d1e472DebcD681B2aBc16e57E \
--network localhost \
--types '["uint256"]' 42
npx hardhat localnet-check
```
By default runs with a delay of 3 seconds to let a call finish.
> Task to check if localnet is still running for CI

- README.md
- package.json
- packages/localnet/src/handleOnEVMCalled.ts
- packages/localnet/src/handleOnEVMDeposited.ts
- packages/localnet/src/index.ts
- yarn.lock
After this is merged, release a new `v3.*.*` version of localnet from main to npm and update bump the version of localnet in https://github.com/zeta-chain/example-contracts/pull/207
> Make localnet compatible with Gateway deployed on testnet

- packages/tasks/src/check.ts
- packages/tasks/src/localnet.ts
- packages/tasks/src/stop.ts
Write both PID and contract addresses to `localnet.json`. Addresses can be used in automated tests so that if localnet addresses change, tests will still be able to read the correct addresses from the JSON.
Basically, to avoid hard-coding them:
https://github.com/zeta-chain/example-contracts/blob/31fb966047a9d73a6ecedc91c8b7f455ef1297c2/examples/nft/scripts/test.sh#L24-L28
For example, https://github.com/zeta-chain/example-contracts/pull/212
> Use `localnet.json` containing both PID and addresses

- packages/localnet/src/createToken.ts
- packages/localnet/src/handleOnAbort.ts
- packages/localnet/src/handleOnEVMCalled.ts
- packages/localnet/src/handleOnEVMDeposited.ts
- packages/localnet/src/handleOnEVMDepositedAndCalled.ts
- packages/localnet/src/handleOnRevertEVM.ts
- packages/localnet/src/handleOnRevertZEVM.ts
- packages/localnet/src/handleOnZEVMCalled.ts
- packages/localnet/src/handleOnZEVMWithdrawn.ts
- packages/localnet/src/handleOnZEVMWithdrawnAndCalled.ts
- packages/localnet/src/index.ts
Related: https://github.com/zeta-chain/protocol-contracts/pull/450
> feat: onAbort

- .github/workflows/run.yml
- README.md
- package.json
- packages/localnet/src/evmExecute.ts
- packages/localnet/src/solanaSetup.ts
- packages/localnet/src/suiSetup.ts
- packages/localnet/src/zetachainCall.ts
- packages/localnet/src/zetachainWithdraw.ts
- packages/localnet/src/zetachainWithdrawAndCall.ts
- packages/tasks/src/solanaDeposit.ts
- packages/tasks/src/solanaDepositAndCall.ts
- Fixed a bug when withdrawing and calling, `evmExecute` was called without gas tokens, so this broke for example universal NFT/FT, when EVM `onCall` expected to get tokens: https://github.com/zeta-chain/standard-contracts/blob/32d34c73083882e32389679e0f2228fe2facd4a3/contracts/token/contracts/evm/UniversalTokenCore.sol#L166-L170
- Add `mnemonic` optional arg to Solana tasks
- Added Solana to CI
- Solana setup:
- generate a key in `~/.config/solana/id.json` if it doesn't exist (otherwise `solana program deploy` complains)
- Airdrop to the default user.
- added `yarn localnet` command to build and run localnet
- Solana deposit/deposit and call import IDL correctly from this npm package
Both Sui and Solana right now are using the same mnemonic for a default user. In both networks, default …
> fix: call evmExecute with gas tokens, Solana improvements

- packages/localnet/src/constants.ts
- packages/localnet/src/evmCall.ts
- packages/localnet/src/evmCustodyWithdrawAndCall.ts
- packages/localnet/src/evmDeposit.ts
- packages/localnet/src/evmDepositAndCall.ts
- packages/localnet/src/evmExecute.ts
- packages/localnet/src/evmOnRevert.ts
- packages/localnet/src/evmSetup.ts
- packages/localnet/src/solanaDeposit.ts
- packages/localnet/src/solanaDepositAndCall.ts
- packages/localnet/src/suiSetup.ts
- packages/localnet/src/zetachainCall.ts
- packages/localnet/src/zetachainDeposit.ts
- packages/localnet/src/zetachainDepositAndCall.ts
- packages/localnet/src/zetachainExecute.ts
- packages/localnet/src/zetachainOnAbort.ts
- packages/localnet/src/zetachainOnRevert.ts
- packages/localnet/src/zetachainSwapToCoverGas.ts
- packages/localnet/src/zetachainWithdraw.ts
- packages/localnet/src/zetachainWithdrawAndCall.ts
* Set 1.5M gas limit for incoming calls (`call`/`depositAndCall`) and for `onRevert`/`onAbort`
* Use `CallOptions.gasLimit` for outgoing calls
* execute EVM onRevert with correct gas limit
* Replace hard-coded chain ID "7001" with `NetworkID.ZetaChain`
> fix: use `CallOptions.gasLimit` for outgoing calls

- packages/localnet/src/index.ts
- packages/localnet/src/solanaSetup.ts
- packages/localnet/src/suiSetup.ts
- packages/tasks/src/localnet.ts
* `--skip` flag to skip chain initialization even if the CLI for that chain is available. This can speed up init process if you only need specific chains, and will help you start localnet even if Sui/Solana setup you have is not compatible with localnet for some reason.
* fixed a bug where Solana token address still showed up in output even if Solana wasn't initialized
This should work:
```
npx hardhat localnet --skip solana
npx hardhat localnet --skip solana,sui
```
> feat: `--skip` param to skip specific chains when launching localnet

- packages/tasks/src/localnet.ts
Right now if Solana is being initialized, and it fails, localnet will just silently not do anything and show standard Anvil output.
In this PR, we change this behavior, so that when Solana init fails, localnet exits with error code 1 and shows why Solana test validator failed to launch.
To test, switch to a version of Solana CLI not supported, for example, 1.18.15:
```
agave-install init 1.18.15
```
```
npx hardhat localnet
```
```
Ledger location: test-ledger
Log: test-ledger/validator.log
Initializing...
Error: failed to start validator: Failed to create ledger at test-ledger: io error: Error checking to unpack genesis archive: Archive error: extra entry found: "._genesis.bin" Regular
```
Switching to 2.0.0 fixes the issue:
```
agave-install init 2.0.0
```
```
npx hardhat localnet
``` …
> fix: throw an error when Solana init fails

- packages/localnet/src/suiSetup.ts
- packages/localnet/src/suiWithdraw.ts
- packages/localnet/src/suiWithdrawAndCall.ts
- packages/localnet/src/zetachainWithdraw.ts
- packages/localnet/src/zetachainWithdrawAndCall.ts
Closes https://github.com/zeta-chain/localnet/issues/114
It has been tested with an advanced example using https://github.com/lumtis/sui-zeta
In progress, needs some refinements to determine how the payload is parsed for the onCall argument.
Tested with https://github.com/lumtis/sui-zeta/blob/main/sources/suizeta.move
- The contract must have a type argument representing the token type (we might possible allow other type argument to extend usability)
- First argument is the withdrawn coin
- Other argument must be shared object or pure
- The function must be called `on_call`, the name of the file must be `universal`, when doing withdraw and call, the package ID is provided as a target, it calls
```
${target}::universal::on_call
```
```
public entry fun on_call<COIN_TYPE>(
coins: …
```
> feat: Sui withdrawAndCall PoC

- packages/localnet/src/zetachainDeposit.ts
- packages/localnet/src/zetachainDepositAndCall.ts
For some reason `asset` was compared with `coin_type` when looking up a foreign coin, which resulted in:
```
[ZetaChain]: Foreign coin not found for asset: 0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f
```
This fixes the issue.
> fix: ZetaChain deposit/deposit & call not being able to find foreign asset

- packages/commands/src/start.ts
Running readline at the top level meant it was executed even when other commands were used.
https://github.com/zeta-chain/cli/pull/12#issuecomment-2838199602
> fix: move readline inside the start command
